import numpy as np
from typing import Optional
from analysis_model.data.StoringandCleaning import StoringAndCleaning
from analysis_model.data.Data_gathering import DataGathering
from analysis_model.analysis.Calculations_DCF import Calculation


class Valuation:
    """Calculates the intrinsic equity value per share and evaluates market pricing.

    This class acts as the final terminal step of the valuation pipeline. It bridge-links 
    macro-enterprise values down into micro per-share metrics to render a deterministic 
    investment verdict (Undervalued, Fairly Valued, or Overvalued).

    Attributes:
        ev (float): Total Enterprise Value generated by the downstream Calculation script.
        cash_and_cash_equivalent (float): Liquid cash holdings for the latest fiscal year.
        total_debts (float): Total obligations/debt outstanding for the latest fiscal year.
        dilluted_shares (float): Total share count assuming all options/convertibles are exercised.
        current_price (float): The actual market trading price of the stock.
        intrisnic_value (Optional[float]): The mathematically derived fair price per share.
        value (Optional[str]): Human-readable textual summary of the investment margin.
    """

    def __init__(self, fetcher: Calculation) -> None:
        """Initializes the valuation calculator using metrics resolved in the Calculation stage.

        Args:
            fetcher (Calculation): An active instance of the Calculation class containing 
                fully rendered enterprise values and sorted balance sheet DataFrames.
        """
        # Extracts data resolved from previous execution phases
        self.ev: float = fetcher.enterprise_value

        # Pulls balance sheet components explicitly pinned to the latest year index
        self.cash_and_cash_equivalent: float = float(
            fetcher.bs.loc[fetcher.latest_year, "Cash"])
        self.total_debts: float = float(
            fetcher.bs.loc[fetcher.latest_year, "Total Debt"])

        # Pulls dynamic current market variables
        self.dilluted_shares: float = float(
            fetcher.extra.loc[0, "Dilluted Shares"])
        self.current_price: float = float(
            fetcher.extra.loc[0, "Current Price"])

        # Placeholders for metrics calculated during execution
        self.intrisnic_value: Optional[float] = None
        self.value: Optional[str] = None

    def calc(self) -> None:
        """Performs equity value bridge conversions and maps valuation margins.

        Derives intrinsic values per share by backing out net debt from operations, 
        then evaluates that figure against real-time market prices.
        """
        # Equity Value Bridge: Equity Value = Enterprise Value + Cash - Debt
        self.equity_value = self.ev + self.cash_and_cash_equivalent - self.total_debts

        # Intrinsic Price per Share = Equity Value / Total Diluted Shares
        self.intrisnic_value = self.equity_value / self.dilluted_shares

        # Absolute differences highlight precise pricing margins regardless of trend direction
        variance = abs(self.intrisnic_value - self.current_price)

        # Margin Evaluation Logic
        if self.intrisnic_value > self.current_price:
            self.value = f"Stock is undervalued by ${variance:.2f}"
        elif self.intrisnic_value == self.current_price:
            self.value = f"Stock is fairly Valued by ${variance:.2f}"
        else:
            self.value = f"Stock is overvalued by ${variance:.2f}"


if __name__ == "__main__":
    data_fetcher = DataGathering("AAPL")
    cleaned = StoringAndCleaning(data_fetch=data_fetcher)
    cleaned.fetch_dataframe()
    cal = Calculation(fetcher=cleaned)
    cal.fetch_data()
    val = Valuation(fetcher=cal)
    val.calc()
    print(val.value)
